sudo: required
services:
  - docker

before_install:
  - docker build -t vbashko/docker-101 -f Dockerfile.dev .

script:
  - docker run -e CI=true vbashko/docker-101 npm run test

deploy:
  edge: true
  project: elasticbeanstalk
  region: "us-west-2"
  app: "docker-101"
  env: "Docker101-env"
  bucket_name: "elasticbeanstalk-us-west-2-592315381426"
  bucket_path: "docker-101"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
